# -*- coding: utf-8 -*-
"""NeuralNetworkShell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nc3d7y2siXcOn6UY58CW0FAiZme-ahl2
"""

from sklearn.utils.fixes import np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import DataLoader, TensorDataset
import math
import numpy as np

# ==== LOAD DATA ====
Flag_normalize = True #Normalize data for better performance
Flag_noise = True

# Define test Data
N = 70
X = np.linspace(-5., 5., num=N,dtype=np.float32)
X1 = X
if (Flag_normalize):
    X = X/ np.max(abs(X))


y_values = []
for i in range(N):
    result = math.sin(9.*X[i]) # increasing the factor (freq) makes training harder
    y_values.append(result)


y1 = np.array(y_values, dtype=np.float32)
if (Flag_normalize):
        y1 = y1 / np.max(abs(y1))


X = X.reshape(-1, 1)
y1 = y1.reshape(-1, 1)

if(Flag_noise):# Add noise
 sigma = 0.025 * np.max(abs(y1))
 mu = 0.
 noise = sigma * np.random.randn(N,1) + mu
 y = y1 + noise
 y = y.astype('float32')


#print (x_train)
#print (y_train)



# ==== PARAMETERS ====
hidden_dim = 32     # number of hidden nodes (this can be changed as needed)
input_dim = X.shape[1]
output_dim = y.shape[1]
batch_size = 64
epochs = 1000
learning_rate = 1e-3


# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# Load data for training and testing
train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=batch_size, shuffle=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=batch_size, shuffle=False)

# ==== DEFINE MODEL ====
class PINN(nn.Module):
    def __init__(self, in_dim, hid_dim, out_dim):
        # Currently three layers with equal size.
        # Can change the number of layers and the dimension of each as needed.
        # Also have dropout ready to add if it is too much data for our computers
        super().__init__()
        self.linear = nn.Linear(in_dim, hid_dim)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hid_dim, hid_dim)
        self.linear3 = nn.Linear(hid_dim, out_dim)
        self.drop = nn.Dropout(p=0.2)

    def forward(self, x):
        x = self.linear(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = self.relu(x)
        x = self.linear3(x)

        return x

# ==== TRAINING ====
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PINN(X.shape[1], hidden_dim, y.shape[1]).to(device) # Output dim should be y.shape[1]
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)


for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * batch_X.size(0)
    avg_loss = total_loss / len(train_loader.dataset)
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.6f}")

import matplotlib.pyplot as plt
if(1): #plot the results

 plt.clf()

 # Get predictions
 predicted = model(torch.from_numpy(X_train.cpu().numpy()).requires_grad_()).data.numpy()

 # Plot true data
 plt.plot(X_train.cpu().numpy(), y_train.cpu().numpy(), 'go', label='True data', alpha=0.5)

 # Plot predictions
 plt.plot(X_train.cpu().numpy(), predicted, 'o', label='Predictions', alpha=0.5)

 # Legend and plot
 plt.legend(loc='best')
 plt.show()

# ==== EVALUATE ====
model.eval()
with torch.no_grad():
    y_test_pred = model(X_test.to(device)).cpu()

reconstruction_error = torch.mean((y_test - y_test_pred) ** 2).item()
print(f"Test reconstruction MSE: {reconstruction_error:.6f}")

