# -*- coding: utf-8 -*-
"""NeuralNetworkShell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nc3d7y2siXcOn6UY58CW0FAiZme-ahl2
"""

from sklearn.utils.fixes import np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import DataLoader, TensorDataset
import math
import numpy as np


# ==== LOAD DATA ====

# Read the csv file
data = pd.read_csv('SI_raw_cleaned.csv')

# Convert to NumPy array
array = data.to_numpy()


# Define test Data
X = array[:,0].astype(np.float32)
S = array[:,2].astype(np.float32)
I = array[:,5].astype(np.float32)


y_s_true = np.array(S, dtype=np.float32)
y_i_true = np.array(I, dtype=np.float32)


# Combine into a 2-column array for S and I
y = np.hstack((y_s_true.reshape(-1, 1), y_i_true.reshape(-1, 1)))


X = X.reshape(-1, 1) # X remains 1D for time input





# ==== PARAMETERS ====
hidden_dim = 350     # number of hidden nodes (this can be changed as needed)
input_dim = X.shape[1]
output_dim = y.shape[1]
batch_size = 64
epochs = 1000
learning_rate = 1e-3


# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# Load data for training and testing
train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=batch_size, shuffle=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=batch_size, shuffle=False)

# ==== DEFINE MODEL ====
class PINN(nn.Module):
    def __init__(self, in_dim, hid_dim, out_dim):
        # Currently three layers with equal size.
        # Can change the number of layers and the dimension of each as needed.
        # Also have dropout ready to add if it is too much data for our computers
        super().__init__()
        self.linear1 = nn.Linear(in_dim, hid_dim)
        self.linear2 = nn.Linear(hid_dim, hid_dim)
        self.linear3 = nn.Linear(hid_dim, hid_dim)
        self.linear4 = nn.Linear(hid_dim, hid_dim)
        self.linear5 = nn.Linear(hid_dim, hid_dim)
        self.linearout = nn.Linear(hid_dim, out_dim)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.linear1(x))
        x = self.relu(self.linear2(x))
        x = self.relu(self.linear3(x))
        x = self.relu(self.linear4(x))
        x = self.relu(self.linear5(x))
        x = self.relu(self.linearout(x))

        return x

# ==== TRAINING ====
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PINN(X.shape[1], hidden_dim, output_dim).to(device) # Output dim should be y.shape[1]
criterion_data = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
beta = 0.01

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        # Ensure input requires gradient for derivative calculation
        batch_X.requires_grad_(True) # Re-added this critical line

        optimizer.zero_grad()
        outputs = model(batch_X)
        # Standard data loss for S and I
        loss_data = criterion_data(outputs, batch_y)

        # Save predicted S and I populations
        S_pred = outputs[:,0:1]
        I_pred = outputs[:,1:2]

        # Calculate first derivatives with respect to time (batch_X)
        dS_dt_pred = grad(S_pred, batch_X, grad_outputs=torch.ones_like(S_pred), create_graph=True, retain_graph=True)[0]
        dI_dt_pred = grad(I_pred, batch_X, grad_outputs=torch.ones_like(I_pred), create_graph=True, retain_graph=True)[0]

        # Calculate the physics loss components
        # Using dS/dt = -beta*S*I/(S+I) and dI/dt = beta*S*I/(S+I)
        dS_dt = -beta * S_pred * I_pred / (S_pred + I_pred)
        dI_dt = beta * S_pred * I_pred / (S_pred + I_pred)

        # Physics loss for S and I components
        loss_physics_S = torch.mean((dS_dt_pred - dS_dt) ** 2)
        loss_physics_I = torch.mean((dI_dt_pred - dI_dt) ** 2)

        # Combine physics losses for both components
        loss_physics = loss_physics_S + loss_physics_I

        # Combine the total losses
        lambda_physics = 1
        loss = loss_data + lambda_physics*loss_physics

        loss.backward()
        optimizer.step()
        total_loss += loss.item() * batch_X.size(0)

    avg_loss = total_loss / len(train_loader.dataset)
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.6f}")

# ==== EVALUATE ====
model.eval()
with torch.no_grad():
    y_test_pred = model(X_test.to(device)).cpu()

reconstruction_error = torch.mean((y_test - y_test_pred) ** 2).item()
print(f"Test reconstruction MSE: {reconstruction_error:.6f}")

